### ISSUE TITLE
Unsupported operand type(s)

### ISSUE THREAD

**Issue by g3rfx** [manuel-calzolari/sklearn-genetic#20]
Hello, 

I tried to run the example in the README. Unfortunately, I got the following error:

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/g3rfx/anaconda3/envs/[redacted]/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/g3rfx/anaconda3/envs/[redacted]/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/g3rfx/anaconda3/envs/[redacted]/lib/python3.6/site-packages/genetic_selection/gscv.py", line 134, in _evalFunction
    scores_mean = np.mean(scores)
  File "<__array_function__ internals>", line 6, in mean
  File "/home/g3rfx/anaconda3/envs/[redacted]/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 3373, in mean
    out=out, **kwargs)
  File "/home/g3rfx/anaconda3/envs/[redacted]/lib/python3.6/site-packages/numpy/core/_methods.py", line 160, in _mean
    ret = umr_sum(arr, axis, dtype, out, keepdims)
TypeError: unsupported operand type(s) for +: 'dict' and 'dict'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ga_feature_subset_selection.py", line 147, in <module>
    ga_feature_selection()
  File "ga_feature_subset_selection.py", line 141, in ga_feature_selection
    selector.fit(X, y)
  File "/home/g3rfx/anaconda3/envs/[redacted]/lib/python3.6/site-packages/genetic_selection/gscv.py", line 282, in fit
    return self._fit(X, y)
  File "/home/g3rfx/anaconda3/envs/[redacted]/lib/python3.6/site-packages/genetic_selection/gscv.py", line 346, in _fit
    stats=stats, halloffame=hof, verbose=self.verbose)
  File "/home/g3rfx/anaconda3/envs/[redacted]/lib/python3.6/site-packages/genetic_selection/gscv.py", line 55, in _eaFunction
    fitnesses = toolbox.map(toolbox.evaluate, invalid_ind)
  File "/home/g3rfx/anaconda3/envs/[redacted]/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/g3rfx/anaconda3/envs/[redacted]/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
TypeError: unsupported operand type(s) for +: 'dict' and 'dict'
```
 My environment is:
```
Ubuntu 20.04.2
Python 3.6.11
sklearn-genetic 0.3.0
scikit-learn 0.24.0
deap 1.3.1
```

Thank you in advance!

**Comment by manuel-calzolari** [comment]
It's because of a change in scikit-learn 0.24. Fixed with commit 7cd52d5, the fix will be in the next release.
